name: jjoin
description: enjoin in join

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  flutter_svg: ^2.0.9
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  intl_translation: ^0.18.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/.env
    - assets/data/